version: 2
sources:
    - name: datafeed_schema
      database: "{{('di_sales')}}"
      schema: raw_schema
      tables:
       - name: raw_customer
       - name: customers
       - name: raw_order
         columns:
           - name: id
             tests:
               - unique
               - not_null

       - name: emp_sal

   